# Generated by Django 5.1.3 on 2024-11-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
    ]
